### ISSUE TITLE
img2img can cause 'CUDA error: device-side assert triggered' with specific combination of steps and strength

### ISSUE THREAD

**Issue by AstraliteHeart** [lstein/stable-diffusion#451]
**Describe your environment**
- GPU: cuda
- VRAM: 24GB (but probably unrelated)
- CPU arch: x86 (but probably unrelated)
- OS: Windows (but probably unrelated)
- Python: Anaconda (but probably unrelated)
- Branch: "On branch main"
- Commit: commit 049ea02fc7e2e0e77908e08455e32f2028e232e9 (HEAD -> main, origin/main, origin/HEAD)

**Describe the bug**
dream.py gets CUDA stuck on valid input combination, requires restart to unstuck

**To Reproduce**
1. Start ./dream.py (I used `set CUDA_VISIBLE_DEVICES=0&set CUDA_LAUNCH_BLOCKING=1&python ./scripts/dream.py`)
2. Run `dream> "A cute little pony" --init_img=not_a_cute_pony.png --strength=0.8 --steps=50 --fit` (Running DDIM Sampling with 40 timesteps)
3. Get a cute pony
4. Run `dream> "A cute little pony" --init_img=H:\\_KERNEL_LIBRARIES\\stable_diffusion\\pp.png --strength=0.99 --steps=50 --fit` (Running DDIM Sampling with 49 timesteps)
5. Get a cute pony, again
6. Run `dream> "A cute little pony" --init_img=H:\\_KERNEL_LIBRARIES\\stable_diffusion\\pp.png --strength=1.01 --steps=50 --fit`
7. No pony with an expected error message `can only work with strength in [0.0, 1.0]`
8. Run `dream> "A cute little pony" --init_img=H:\\_KERNEL_LIBRARIES\\stable_diffusion\\pp.png --strength=1.0 --steps=50 --fit`
9. There is no cute pony but a CUDA error instead [see below]
11. The CUDA is now stuck and going back to working arguments still fail until dream.py is restarted

```
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:111: block: [0,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Generating:   0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "...\stable-diffusion\ldm\simplet2i.py", line 382, in prompt2image
    image = make_image(x_T)
  File "...\stable-diffusion\ldm\simplet2i.py", line 529, in make_image
    z_enc = sampler.stochastic_encode(
  File "...\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "...\stable-diffusion\ldm\models\diffusion\ddim.py", line 368, in stochastic_encode
    extract_into_tensor(sqrt_alphas_cumprod, t, x0.shape) * x0
  File "...\stable-diffusion\ldm\modules\diffusionmodules\util.py", line 136, in extract_into_tensor
    out = a.gather(-1, t)
RuntimeError: CUDA error: device-side assert triggered
```

**Expected behavior**
Either strength should be limited to be [0, 1) or this is an off by one error to be fixed

**Additional context**
I do not understand SD code enough to make a good call here, but it looks like in stable-diffusion\ldm\modules\diffusionmodules\util.py:L133
```
def extract_into_tensor(a, t, x_shape):
    b, *_ = t.shape
    out = a.gather(-1, t)
    return out.reshape(b, *((1,) * (len(x_shape) - 1)))
```

dies when `t` and `a.shape` are the same (and works correctly when `a.shape > t`)

**Comment by lstein** [comment]
It turns out that strength cannot be 1.0. I believe this was fixed in the development branch. Could you check that out and confirm?
